Add variable to conditionally install dependencies
ccremer/ansible-lsyncd pull request #1
Opened 2018-04-05 19:42 UTC by jyaworski

2018-04-05 21:20 UTC, ccremer requested changes
Thank you for your contribution! I think it could be improved a bit though

2018-04-05 21:20 UTC, ccremer commented on vars/main.yml
> +lsyncd_install_dependencies: true
Remove this line please. This variable is already defined in the defaults\main.yml

2018-04-05 21:20 UTC, ccremer commented on README.md
> +lsyncd_install_dependencies: false # install dependencies outside of this role
It should be set to true, as it's defined in defaults\main.yml

2018-04-05 21:20 UTC, ccremer commented on tasks/install-debian.yml
> +  when: "{{ lsyncd_install_dependencies }}"
I think boolean variables don't need " and {{ in the when clause, just declare `when: lsyncd_install_dependencies`

2018-04-05 21:20 UTC, ccremer commented on tasks/install-centos.yml
> +  when: "{{ lsyncd_install_dependencies }}"
I think boolean variables don't need " and {{ in the when clause, just declare `when: lsyncd_install_dependencies`

2018-04-06 13:31 UTC, jyaworski commented
@ccremer I've addressed your comments and rebased.

2018-04-06 13:49 UTC, ccremer approved these changes

2018-04-06 13:49 UTC, merged